### HERE IS TWO SOLUTIONS TO THE CREDIT RISK ANALYSIS DONE IN THE SAME STYLE

**SOLUTION 1**

In [27]:
# importing all the necesaary libraries and files 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [28]:
# importing the dataset, one hot encoding and label encoding 
df = pd.read_csv("databases/csvs/credit_risk.csv")
column_to_drop = 'Id'
df = df.drop(column_to_drop, axis=1)
df = pd.get_dummies(df, columns=['Home', 'Intent', 'Default'])  # One-hot encoding 
df

Age  Income  Emp_length  Amount   Rate  Status  Percent_income  \
0       22   59000       123.0   35000  16.02       1            0.59   
1       21    9600         5.0    1000  11.14       0            0.10   
2       25    9600         1.0    5500  12.87       1            0.57   
3       23   65500         4.0   35000  15.23       1            0.53   
4       24   54400         8.0   35000  14.27       1            0.55   
...    ...     ...         ...     ...    ...     ...             ...   
32576   57   53000         1.0    5800  13.16       0            0.11   
32577   54  120000         4.0   17625   7.49       0            0.15   
32578   65   76000         3.0   35000  10.99       1            0.46   
32579   56  150000         5.0   15000  11.48       0            0.10   
32580   66   42000         2.0    6475   9.99       0            0.15   

       Cred_length  Home_MORTGAGE  Home_OTHER  Home_OWN  Home_RENT  \
0                3              0           0         0          1   
1                2              0           0         1          0   
2                3              1           0         0          0   
3                2              0           0         0          1   
4                4              0           0         0          1   
...            ...            ...         ...       ...        ...   
32576           30              1           0         0          0   
32577           19              1           0         0          0   
32578           28              0           0         0          1   
32579           26              1           0         0          0   
32580           30              0           0         0          1   

       Intent_DEBTCONSOLIDATION  Intent_EDUCATION  Intent_HOMEIMPROVEMENT  \
0                             0                 0                       0   
1                             0                 1                       0   
2                             0                 0                       0   
3                             0                 0                       0   
4                             0                 0                       0   
...                         ...               ...                     ...   
32576                         0                 0                       0   
32577                         0                 0                       0   
32578                         0                 0                       1   
32579                         0                 0                       0   
32580                         0                 0                       0   

       Intent_MEDICAL  Intent_PERSONAL  Intent_VENTURE  Default_N  Default_Y  
0                   0                1               0          0          1  
1                   0                0               0          1          0  
2                   1                0               0          1          0  
3                   1                0               0          1          0  
4                   1                0               0          0          1  
...               ...              ...             ...        ...        ...  
32576               0                1               0          1          0  
32577               0                1               0          1          0  
32578               0                0               0          1          0  
32579               0                1               0          1          0  
32580               1                0               0          1          0  

[32581 rows x 20 columns]

In [29]:
# Handling missing values with SimpleImputer
imputer = SimpleImputer(strategy='mean')  # You can use other strategies like 'median' or 'most_frequent'
df_SI = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

In [30]:
# X and y
X = df_SI.iloc[:,:5].values
y = df_SI.iloc[:,5].values

In [31]:
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() # remember this. the goal of standardization is to have all the values of the features in the same range. -3 & +3
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test) 

In [33]:
# Initialize the Random Forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier = classifier = RandomForestClassifier(n_estimators = 100, max_depth = 50, criterion = "entropy",random_state=42) # always use entropy when using decisin trees 
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=50, random_state=42)

In [34]:
y_preds = classifier.predict(X_test)
print(np.concatenate((y_preds.reshape(len(y_preds),1),y_test.reshape(len(y_test),1)),1))

[[1. 0.]
 [1. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [35]:
cm =confusion_matrix(y_test, y_preds)
print(cm)

acc=accuracy_score(y_test, y_preds)
print(acc) 
print(f" Model Accuracy: {acc * 100:.2f}%")

[[4806  266]
 [ 536  909]]
0.8769372410618382
 Model Accuracy: 87.69%


In [36]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 87.18 %
Standard Deviation: 0.41 %


**SOLUTION 2**

In [37]:
# importing all the necesaary libraries and files 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [38]:
# importing the dataset, one hot encoding and label encoding 
df = pd.read_csv("databases/csvs/credit_risk.csv")
column_to_drop = 'Id'
df = df.drop(column_to_drop, axis=1)
df = pd.get_dummies(df, columns=['Home', 'Intent'])  # One-hot encoding 
label_encoder = LabelEncoder()
df['Default'] = label_encoder.fit_transform(df['Default'])
df

Age  Income  Emp_length  Amount   Rate  Status  Percent_income  \
0       22   59000       123.0   35000  16.02       1            0.59   
1       21    9600         5.0    1000  11.14       0            0.10   
2       25    9600         1.0    5500  12.87       1            0.57   
3       23   65500         4.0   35000  15.23       1            0.53   
4       24   54400         8.0   35000  14.27       1            0.55   
...    ...     ...         ...     ...    ...     ...             ...   
32576   57   53000         1.0    5800  13.16       0            0.11   
32577   54  120000         4.0   17625   7.49       0            0.15   
32578   65   76000         3.0   35000  10.99       1            0.46   
32579   56  150000         5.0   15000  11.48       0            0.10   
32580   66   42000         2.0    6475   9.99       0            0.15   

       Default  Cred_length  Home_MORTGAGE  Home_OTHER  Home_OWN  Home_RENT  \
0            1            3              0           0         0          1   
1            0            2              0           0         1          0   
2            0            3              1           0         0          0   
3            0            2              0           0         0          1   
4            1            4              0           0         0          1   
...        ...          ...            ...         ...       ...        ...   
32576        0           30              1           0         0          0   
32577        0           19              1           0         0          0   
32578        0           28              0           0         0          1   
32579        0           26              1           0         0          0   
32580        0           30              0           0         0          1   

       Intent_DEBTCONSOLIDATION  Intent_EDUCATION  Intent_HOMEIMPROVEMENT  \
0                             0                 0                       0   
1                             0                 1                       0   
2                             0                 0                       0   
3                             0                 0                       0   
4                             0                 0                       0   
...                         ...               ...                     ...   
32576                         0                 0                       0   
32577                         0                 0                       0   
32578                         0                 0                       1   
32579                         0                 0                       0   
32580                         0                 0                       0   

       Intent_MEDICAL  Intent_PERSONAL  Intent_VENTURE  
0                   0                1               0  
1                   0                0               0  
2                   1                0               0  
3                   1                0               0  
4                   1                0               0  
...               ...              ...             ...  
32576               0                1               0  
32577               0                1               0  
32578               0                0               0  
32579               0                1               0  
32580               1                0               0  

[32581 rows x 19 columns]

In [39]:
# Handling missing values with SimpleImputer
imputer = SimpleImputer(strategy='mean')  # You can use other strategies like 'median' or 'most_frequent'
df_SI = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

In [40]:
# X and y
X = df_SI.iloc[:,:7].values
y = df_SI.iloc[:,7].values

In [41]:
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() # remember this. the goal of standardization is to have all the values of the features in the same range. -3 & +3
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test) 

In [43]:
# Initialize the Random Forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier = classifier = RandomForestClassifier(n_estimators = 100,max_depth = 10, criterion = "entropy",random_state=42) # always use entropy when using decisin trees 
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=10, random_state=42)

In [44]:
y_preds = classifier.predict(X_test)
print(np.concatenate((y_preds.reshape(len(y_preds),1),y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 1.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [45]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
cm =confusion_matrix(y_test, y_preds)
print(cm)

acc=accuracy_score(y_test, y_preds)
print(acc) 
print(f" Model Accuracy: {acc * 100:.2f}%")

[[5036  286]
 [ 851  344]]
0.8255332208071199
 Model Accuracy: 82.55%


In [46]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 82.69 %
Standard Deviation: 0.48 %
